name: crypdo
description: Crypdo mobile client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: any
  logger: any
  get_it: ^7.1.3
  dartz: ^0.10.0-nullsafety.2
  flutter_bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.2
  json_serializable: ^4.1.3
  shared_preferences: ^2.0.6
  uuid: ^3.0.4
  flutter_native_splash: ^1.1.8+4
  collection: ^1.15.0
  http_parser: ^4.0.0
  hexagon: ^0.2.0-nullsafety.1
  flutter_svg: ^0.22.0
  blur: ^3.0.0
  pie_chart: ^5.0.0
  intl: ^0.17.0



dev_dependencies:
  retrofit_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/ui/

  fonts:
    - family: IranSansLight
      fonts:
        - asset: assets/fonts/IRANSansX-Light.ttf
    - family: IranSansRegular
      fonts:
        - asset: assets/fonts/IRANSansX-Regular.ttf

flutter_native_splash:
  image: assets/images/splash.png
